### ISSUE TITLE
How to run the benchmark tests

### ISSUE THREAD

**Issue by haimingw0428** [oxfordcontrol/osqp_benchmarks#4]
Hi, 

I am using Ubuntu system. Should I put the osqp_benchmarks to some specific location? Because when I tried to run run_benchmark_problems.py, the terminal shows ImportError: No module named osqp.

**Comment by goulart-paul** [comment]
This is just the benchmarks repository.   You still need to actually install osqp.   See [here](https://osqp.org/docs/get_started/python.html).

**Comment by haimingw0428** [comment]
Thank you so much for your quick response. Actually, I installed osqp but not using pip install. I build and make install, and can find them in /usr/local/...

**Comment by goulart-paul** [comment]
Are you now able to run the benchmarks?   If not, are you able to solve an example problem in python like those shown in the OSQP interface documentation pages?

**Comment by haimingw0428** [comment]
I figured it out. Thanks.
