### ISSUE TITLE
Some issues from qplib problem

### ISSUE THREAD

**Issue by haimingw0428** [oxfordcontrol/osqp_benchmarks#5]
Hi,

I tried some qplib problem benchmark test, but found there are some non-convex warnings. I was wondering if you met the similar issues? Such as for "QPLIB_0343",  OSQP showed "ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex".

**Comment by goulart-paul** [comment]
That problem appears to be non-convex.  See here: http://qplib.zib.de/QPLIB_0343.html

It says there that the number of negative eigenvalues in the objective function is 24 (out of 50).  OSQP throws an error if it detects any negative eigenvalues in the objective.

**Comment by haimingw0428** [comment]
Thank you so much for explanations. Since "QPLIB_0343" gives the solution as objvar = -6.386014981598350, so I thought it should be solvable by OSQP.
